MRSD '23 Team G: Docker for PyTorch
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #132
Opened 2022-12-06 00:30 UTC by PallaviMadhukar

2022-12-11 18:01 UTC, smbryan requested changes
This is really close to be ready to merge. Please drop the HTML and use the Markdown equivalent.

2022-12-11 18:01 UTC, smbryan commented on wiki/tools/docker-for-pytorch.md
> +<em><strong>
Please don't mix HTML in with the Markdown; Jekyll doesn't handle it how you'd expect. 

CC: @nevalsar

2023-09-28 06:44 UTC, nevalsar requested changes
(See earlier review comments)

2024-04-27 18:21 UTC, nevalsar commented
Contributor unresponsive - will fix and merge these changes in a separate MR.

2024-04-27 18:21 UTC, closed without merging