TeamA F22: External state estimation
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #133
Opened 2022-12-06 16:19 UTC by John-HarringtonNZ

This is an update of the robotics-knowledge-base website, with content relating to GPS-lacking sensing systems including UltraWideband beacons and robotic total stations. This acts as Team A's Fall 2022 contribution as part of the MRSD Project Course (16-682).

2022-12-11 18:11 UTC, smbryan requested changes
I appreciate the fresh content here. Some minor housekeeping before we can merge this in.

2022-12-11 18:11 UTC, smbryan commented on wiki/sensing/robotic-total-stations.md
> +## Introduction
The first paragraph (or the first 100 words) becomes the page description. The blurb for this page will just read "## Introduction"...

I'd recommend dropping this line and keeping the first page as-is. 

CC: @nevalsar

2022-12-11 18:11 UTC, smbryan commented on wiki/sensing/ultrawideband-beacon-positioning.md
> +This page will go into detail about to get started with UltraWideband positioning, particuarly with the [DWM1001-Dev module](https://www.qorvo.com/products/p/DWM1001-DEV).
Same issue here. The link would also be displayed in its native markdown if left. Please rewrite to omit any headers (e.g. `## Introduction`) or Markdown. 

Your "Externally Referenced" article below is a particularly strong intro. I'd model follow that example.

CC: @nevalsar

2023-09-28 06:43 UTC, nevalsar requested changes
(See earlier review comments)

2024-04-27 18:31 UTC, nevalsar commented
Contributor unresponsive - will raise these changes in a separate MR fixing issues.

2024-04-27 18:31 UTC, closed without merging