Added detailed page on using the Ultimaker Series printers
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #137
Opened 2022-12-08 04:51 UTC by HardikSingh97

Wiki Entry for MRSD Project Team J in Class of 2022 (Project DAIR).

2022-12-15 20:19 UTC, nevalsar commented on wiki/fabrication/ultimaker-series.md
> +<figcaption align = "center"><b>Figure 1: Ultimaker Cura PREPARE screen when preparing a print. </b></figcaption>
@smbryan do you know if `<figcaption>` tags are supported by our markdown flavor?

2022-12-15 20:40 UTC, nevalsar requested changes
Good PR! It still requires one necessary change and a couple of semantic recommendations.

2022-12-15 20:40 UTC, nevalsar commented on wiki/fabrication/ultimaker-series.md
> +![Ultimaker Cura Screen](assets/ultimaker_fig3.jpg)
@HardikSingh97 This image link is broken - please update (extensions are case-sensitive!).

2022-12-15 20:40 UTC, nevalsar commented on wiki/fabrication/ultimaker-series.md
> +## Wrong print settings
Is this not meant to be a third-level heading under 'Typical Failures'?

2022-12-15 20:40 UTC, nevalsar commented on wiki/fabrication/ultimaker-series.md
> +**7** - Take a look at how long and how much material this print will take  *at the current print settings*. If either of these numbers are unsuitable to you, hope back over to the top bar menu and c
There is a change from a `(Circle x)` format of referencing the markup in the figures to a numbered list format here - as a reader I'm confused why all of a sudden a numbered list appears starting at point 6! Consider revising.

2022-12-15 22:47 UTC, smbryan commented
Good catch! Looking at the kramdown documentation, it looks like not. Anything even vaguely HTML can throw Jekyll for a loop.

On a positive note, it looks like Jekyll now supports changing backends. But, we'll have to look into how we do that within Github Page's limitations.
-------- Original Message --------
On Dec 15, 2022, 15:19, Nevin Valsaraj wrote:

> @nevalsar commented on this pull request.
>
> ---------------------------------------------------------------
>
> In [wiki/fabrication/ultimaker-series.md](https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/pull/137#discussion_r1050099567):
>
>> +
> +In the MS in Robotic Systems Development (MRSD) Lab at CMU, there are four printers from the Ultimaker series. These can be used in essentially the same way. The printers are:
> +- 2 x Ultimaker 3 (no longer manufactured by Ultimaker)
> +- 2 x Ultimaker S3
> +
> +
> +## Software
> +The Ultimaker Series of printers uses the [Ultimaker Cura](https://ultimaker.com/software/ultimaker-cura) software to slice STL files for printing. When setting up a print, it is important to crosscheck your print settings with the printer you have on hand. This is expanded on below.
> +
> +
> +## Setting up a print
> +Using your favorite CAD Sofware (i.e. Solidworks), prepare an STL file of your model for printing. Open up CURA, and use the folder icon in the top left of your window (Circle 1) to select the STL file(s) you have prepared.
> +
> +Using the options on the left side of the screen (Circle 2), move your piece(s) around. Using these controls, you can change the orientaiton of the part, as well as its location on the build plate. Make sure that part is oriented to minimize overhangs, and if you have multiple pieces, that the pieces are not too close to each other.
> +
> +<figcaption align = "center"><b>Figure 1: Ultimaker Cura PREPARE screen when preparing a print. </b></figcaption>
>
> ***@***.***(https://github.com/smbryan) do you know if <figcaption> tags are supported by our markdown flavor?
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/RoboticsKnowledgebase/roboticsknowledgebase.github.io/pull/137#pullrequestreview-1219891791), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ADYZWP4OQM6H6X5DU73JXZ3WNN4ORANCNFSM6AAAAAASXVIW7U).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-12-16 05:56 UTC, nevalsar commented on wiki/fabrication/ultimaker-series.md
> +<figcaption align = "center"><b>Figure 1: Ultimaker Cura PREPARE screen when preparing a print. </b></figcaption>
Please remove the HTML tag used in the caption - these tags will break our markdown renderer.

2026-04-27 06:31 UTC, nevalsar commented
I've updated the PR with several fixes to align with project standards and address previous review feedback:

- Moved images to the standard directory (`/assets/images/fabrication/`) and updated to absolute paths.
- Replaced unsupported HTML (`<figcaption>`, `<b>`) with standard Markdown.
- Standardized figure referencing consistency (Circle X format).
- Resolved merge conflicts and updated the fabrication category index.
- Fixed case-sensitive image extensions and improved the References section.

The article now passes the automated audit and is ready for final review.

2026-04-27 06:32 UTC, nevalsar approved these changes

2026-04-27 06:34 UTC, merged