Add guide for setting up and using Mapviz in ROS2
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #138
Opened 2022-12-08 05:31 UTC by shrijitsingh99

Shows how to setup Mapviz in ROS2. Includes some helper scripts and their explanation that makes integration with robots easier.

2022-12-11 18:30 UTC, smbryan requested changes
Great start. Needs some minor housekeeping before we can merge.

2022-12-11 18:30 UTC, smbryan commented on _data/navigation.yml
> +         url: /wiki/planning/mapviz/
Whitespace. `url:` should be aligned with title. Some YAML parsers will throw an error if not. 

You're using spaces, right?

CC: @nevalsar

2022-12-11 18:30 UTC, smbryan commented on wiki/tools/mapviz.md
> +# Mapviz for Map Based Visualization in ROS2
Missing page meta information. Please see the template.

Also, the first paragraph shouldn't have a header (i.e. "# Mapviz...") or any markdown. Jekyll uses the first paragraph (or the first 100 words) to generate a blurb for your entry. Unfortunately, it pulls what it finds verbatim.

CC: @nevalsar

2023-09-28 06:42 UTC, nevalsar requested changes
(See earlier review comments)

2024-04-27 18:40 UTC, nevalsar commented
Contributor unresponsive - will raise these changes as a separate MR fixing issues.

2024-04-27 18:40 UTC, closed without merging