Team F: Multi robot Navigation stack design
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #140
Opened 2022-12-08 14:17 UTC by indraneelpatil

2022-12-11 18:36 UTC, smbryan requested changes
One item to address, then this should be ready to merge. Great submission.

2022-12-11 18:36 UTC, smbryan commented on wiki/planning/multi-robot-planning.md
> +date: {}
Date?

CC: @nevalsar

2022-12-12 00:24 UTC, indraneelpatil commented on wiki/planning/multi-robot-planning.md
> +date: {}
Done! @smbryan @nevalsar Thanks!

2022-12-12 03:23 UTC, nevalsar commented
That should fix it. Merging.

2022-12-12 03:23 UTC, merged