Team H - NLP for robotics
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #143
Opened 2022-12-12 22:07 UTC by sudo-prakhar

2022-12-15 17:06 UTC, smbryan commented
We're just missing an update to `navigation.yml`

CC: @nevalsar

2022-12-15 20:03 UTC, nevalsar commented
@sudo-prakhar you can take a look at #139 for an example of changes required in `navigation.yml` for a new page.

2022-12-15 21:06 UTC, nevalsar requested changes

2022-12-15 21:06 UTC, nevalsar commented on wiki/machine-learning/nlp_for_robotics.md
> +---
@sudo-prakhar This is a new page and requires an addition to the `navigation.yml`. You can take a look at #139 for an example of the changes required.

2022-12-16 06:04 UTC, nevalsar requested changes
@sudo-prakhar You have merged from the master branch instead of rebasing your PR branch off it, which will lead to a circular history instead of a linear one. Can you fix that? 

Please remove the last merge commit and rebase your branch off the latest master branch.

2022-12-16 14:38 UTC, smbryan commented
@nevalsar, Circular Git Histories? What an urban legend!

Recommended Reading: https://wiki.emulab.net/wiki/everything-you-need-to-unlearn-about-git

Merging in the master branch is a valid method of resolving potential conflicts. I'm guessing that @sudo-prakhar is still getting comfortable with Git & GitHub workflows (since it was easier to close the previous PR and open a new one when I requested changes). It would be good to brush up on rebasing, but isn't required in this case.

2022-12-21 20:27 UTC, nevalsar commented
@smbryan I understand the needless 'linear history' confusion, but as per my understanding `git blame` loses usefulness if changes are commited back and forth across branches. Also, I felt there is no need to have the last merge commit as part of this PR since there is no merge conflict to resolve and changes in this PR are completely standalone.   

I usually require PRs to my repos to be rebased where possible but I agree that can be relaxed.

2022-12-21 20:29 UTC, merged