Troubleshooting Ubuntu Dual Boot Page
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #149
Opened 2023-04-30 07:29 UTC by sthirupa

Team G Spring 2023 MRSD Wiki Entry Final - Troubleshooting Ubuntu Dual Boot

2023-05-01 22:18 UTC, PallaviMadhukar approved these changes

2023-05-08 21:01 UTC, nevalsar requested changes
Good start to the PR, but needs some work before merging.

Please re-raise the review request once changes are made.

2023-05-12 05:00 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +> It is recommended to begin the dual boot process as soon as possible in case things go wrong so that project time is not wasted trying to reinstall Ubuntu for the fourth time, or wasting $300 on me
Made the appropriate changes in latest commits.

2023-05-12 05:00 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +Go to www.releases.ubuntu.com and select an LTS Release. Check with someone to know which version is trusted as the latest release may not work with all software needed. Download the .iso file for th
Made the appropriate changes in latest commits.

2023-05-12 05:01 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +Go to www.releases.ubuntu.com and select an LTS Release. Check with someone to know which version is trusted as the latest release may not work with all software needed. Download the .iso file for th
Made the appropriate changes in latest commits.

2023-05-12 05:01 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +## Further Reading
Made the appropriate changes in latest commits.

2023-05-12 05:01 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +Partitions of unallocated data can only be incorporated into another partition using Extend Volume if the unallocated partition is to the right of an existing partition with an OS. If there are multi
Made the appropriate changes in latest commits.

2023-05-12 05:01 UTC, sthirupa commented on wiki/computing/troubleshooting-ubuntu-dual-boot.md
> +Creating the Ubuntu partition on the hard drive for the dual boot can be done while installing Ubuntu from the USB drive but it is better to do it while in Windows Go to the Disk Management page in W
Made the appropriate changes in latest commits.

2023-09-28 06:38 UTC, nevalsar approved these changes
There is some scope to revise the text in this article, but the difficulty in writing a comprehensive troubleshooting guide for niche topics is acknowledged. I'm okay with merging this and leaving the task of improving this page to a separate PR.

2023-09-28 06:38 UTC, merged