Team B Unitree Go1 Pull Request
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #154
Opened 2023-05-04 02:47 UTC by TingWeiWong

2023-05-07 21:53 UTC, TingWeiWong commented
Added docker security wiki page

2023-05-22 17:19 UTC, smbryan requested changes
Excellent start. A few more items are required before we can pull this in.

2023-05-22 17:19 UTC, smbryan commented on assets/images/docker_socket.png
These asset files shouldn't be in the root-level assets, but rather `wiki/tools/assets` or `wiki/common-platforms/assets`.

2023-05-22 17:19 UTC, smbryan commented on wiki/common-platforms/unitree-go1.md
> +(Note: This section contains the latest information as of May 2023)
I'd recommend moving this to the bottom of the introduction.

2023-05-22 17:19 UTC, smbryan commented on wiki/common-platforms/unitree-go1.md
> +![Form_Factor](../../assets/images/form_factor.png)
Please move the assets to the parent assets directory. Then, this line should read `![Form_Factor](assets/images/form_factor.png)`

2023-09-28 05:34 UTC, nevalsar requested changes
Please see and resolve existing review comments.

2023-12-13 21:10 UTC, TingWeiWong commented
Fixed image path issues.

2024-04-27 18:47 UTC, nevalsar requested changes
Thank you for fixing the earlier issues! 
Please fix the one image that looks corrupted and we can merge this in.

2024-04-27 18:47 UTC, nevalsar commented on wiki/common-platforms/assets/unitree_side.png
Image is corrupted and not viewable - please replace.

2024-04-28 05:35 UTC, TingWeiWong commented on wiki/common-platforms/assets/unitree_side.png
Hi, the unitree-side.png on my side is also not displaying. Unfortunately I couldn't find the original image, I'm removing it from the markdown.

2024-04-28 06:45 UTC, nevalsar approved these changes
Looks good! Merging.

2024-04-28 06:47 UTC, nevalsar approved these changes

2024-04-28 06:49 UTC, merged