Team B Wiki Entry - Fall 2020
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #90
Opened 2020-12-07 15:34 UTC by brysonjones

This commit has two entries added: 
- A* Planning Implementation Guide
- RTK GPS

2020-12-08 14:39 UTC, smbryan requested changes
Solid submission. There are two lines in the navigation file that need attention. Will be ready to merge once those are fixed.

2020-12-08 14:39 UTC, smbryan commented on _data/navigation.yml
> +	url: /wiki/sensing/gps/
Double check the white space here. Should be spaces and the 'u' of url should line up with the 't' of title.

2020-12-08 14:39 UTC, smbryan commented on _data/navigation.yml
> +	url: /wiki/planning/astar_planning_implementation_guide/
White space.

2020-12-09 05:12 UTC, brysonjones commented
Just added the changes!

2020-12-09 15:04 UTC, smbryan requested changes
Almost! With the corrected directories, we need to change the path to the file.

2020-12-09 15:04 UTC, smbryan commented on wiki/planning/astar_planning_implementation_guide.md
> +![](/assets/astar_h_viz.png)
All asset paths should be relative -> `assets/astar_h_viz.png`.

Drop the first `/` and you'll be good. Please make sure you get them all.

2020-12-10 05:01 UTC, brysonjones commented
Just updated. Let me know if there are any other issues!

2020-12-14 21:15 UTC, smbryan approved these changes

2020-12-14 21:16 UTC, merged

2020-12-14 21:17 UTC, smbryan commented
All set! Looking forward to checking out yinz posters soon.