TEAM D WIKI Entry 2020 Fall
RoboticsKnowledgebase/roboticsknowledgebase.github.io pull request #91
Opened 2020-12-07 22:49 UTC by ZhekaiJin

Add the proposed Python Libraries for Reinforcement Learning for Team D
Author: Alvin Huang, Rohan Pandya, Mayank Singal, Karthik Arcot, Scott Jin

2020-12-07 22:56 UTC, ZhekaiJin commented
Corrected wrong path hiding existing page in the existing repo

2020-12-08 14:40 UTC, smbryan commented on _data/navigation.yml
> +        url: wiki/machine-learning/custom-semantic-data/
Thank you for correcting this.

2020-12-08 14:46 UTC, smbryan requested changes
Solid submission. The first paragraph needs some attention and we're ready to merge. Sadly, this is a limitation of Jekyll.

2020-12-08 14:46 UTC, smbryan commented on wiki/machine-learning/python-libraries-for-reinforcement-learning.md
> +[Reinforcement Learning (RL)](https://en.wikipedia.org/wiki/Reinforcement_learning)is a machine learning approach for teaching agents how to solve tasks by trial and error. More specifically, RL is m
The links in the header here won't display properly when the summaries get generated. 

From the template: `The first 100 words are used as an excerpt on the Wiki's Index. No images, HTML, or special formating should be used in this section as it won't be displayed properly.`

They should be moved to References or below the first subheading (i.e. "Spinning Up")

2020-12-18 04:31 UTC, ZhekaiJin commented on wiki/machine-learning/python-libraries-for-reinforcement-learning.md
> +[Reinforcement Learning (RL)](https://en.wikipedia.org/wiki/Reinforcement_learning)is a machine learning approach for teaching agents how to solve tasks by trial and error. More specifically, RL is m
Thanks and I moved them to See Also links!

2020-12-18 20:34 UTC, merged

2020-12-18 20:35 UTC, smbryan commented
Merged. Enjoy your break!